##http 配置
server.port = 10046
server.contextPath=/ai-server
# http.page = classpath:/page

# http.404 = /showcase/404
# http.500 = /showcase/500
# 页面文件缓存时间，开发时设置成0，生产环境可以设置成1小时(3600)，10分钟(600)等，单位：秒
# http.maxLiveTimeOfStaticRes=0